/* Crear tablespace TBSGAMARK */ 
CREATE TABLESPACE TBSGAMARK 
DATAFILE 'tbsgamark.dbf' 
SIZE 300M;

/* Listar tablespaces del servidor de base de datos */ 
SELECT TABLESPACE_NAME, STATUS, CONTENTS
FROM USER_TABLESPACES;

/* Activar el parámetro _ORACLE_SCRIPT */
ALTER SESSION SET "_oracle_script"= TRUE;

/*Crear usuario gmarket */ 
CREATE USER gmarket IDENTIFIED BY ORCL1234
DEFAULT TABLESPACE TBSGAMARK TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TBSGAMARK;

/* Asignando permisos para la gestión de tablespace */
GRANT CREATE SESSION TO gmarket;
GRANT CREATE TABLE TO gmarket; 
GRANT CREATE VIEW TO gmarket; 
GRANT CREATE PROCEDURE TO gmarket; 
GRANT CREATE TRIGGER TO gmarket; 
GRANT CREATE SEQUENCE TO gmarket; 
GRANT CREATE JOB TO gmarket;
GRANT UNLIMITED TABLESPACE TO gmarket;

/* LISTADO DE USUARIOS */
SELECT * FROM DBA_USERS;



/* Eliminar tablespace */
DROP TABLESPACE TBSGAMARK 
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

/* Listar tablespaces de la base de datos */
SELECT TABLESPACE_NAME, STATUS, CONTENTS
FROM USER_TABLESPACES;
 
/* Activar el parámetro _ORACLE_SCRIPT */
ALTER SESSION SET "_oracle_script"= TRUE;

/* Eliminar usuario */
DROP USER URBANA CASCADE;

/* Listar usuarios */
SELECT * FROM DBA_USERS;

/* ============================================= */
/*               ACTIVIDAD DE CLASES             */
/* ============================================= */

/* PRIMERO CREAMOS NUESTRA TABLSEPCA*/
CREATE TABLESPACE TBSURBANA
DATAFILE 'tbsurbana.dbf'
SIZE 300M;

/* LUEGO LISTAMOS */
SELECT TABLESPACE_NAME, STATUS, CONTENTS
FROM USER_TABLESPACES;

/* LE DAMOS LOS PARAMTEROS*/
ALTER SESSION SET "_oracle_script" = TRUE;

/* CREAMOS UN USUARIO */
CREATE USER urbana IDENTIFIED BY ORCL1234
DEFAULT TABLESPACE TBSURBANA TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TBSURBANA;

/* LE DAMOS PRIVILEGIOS */
GRANT CREATE SESSION TO urbana;
GRANT CREATE TABLE TO urbana; 
GRANT CREATE VIEW TO urbana; 
GRANT CREATE PROCEDURE TO urbana; 
GRANT CREATE TRIGGER TO urbana; 
GRANT CREATE SEQUENCE TO urbana; 
GRANT CREATE JOB TO urbana;
GRANT UNLIMITED TABLESPACE TO urbana;

/* LUEGO LISTAMOS LOS USUARIOS */
SELECT * FROM DBA_USERS;








