/* Crear tabla PERSONA */
CREATE TABLE persona (
   IDPER INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
   DNIPER CHAR(8),
   NOMPER VARCHAR2(60),
   APEPER VARCHAR2(80),
   EMAPER VARCHAR2(80),
   CELPER CHAR(9),
   TIPPER CHAR(1),
   ESTPER CHAR(1) DEFAULT 'A',
   FECNACPER DATE,
   CONSTRAINT persona_pk PRIMARY KEY (IDPER)
);
COMMIT;

/* Crear tabla CATEGORIA */
CREATE TABLE categoria (
   IDCAT INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
   NOMCAT VARCHAR2(60),
   CONSTRAINT categoria_pk PRIMARY KEY (IDCAT)
);
COMMIT;

/* Crear tabla PRODUCTO */
CREATE TABLE producto (
   CODPROD CHAR(3),
   NOMPRO VARCHAR2(50),
   IDCAT INT,
   PREPRO NUMBER(8,2),
   STOCKPRO INT,
   ESTPRO CHAR(1) DEFAULT 'A',
   CONSTRAINT producto_pk PRIMARY KEY (CODPROD),
   CONSTRAINT producto_categoria_fk FOREIGN KEY (IDCAT) REFERENCES categoria(IDCAT)
);
COMMIT;

/* Crear tabla VENTA */
CREATE TABLE venta (
   IDVEN INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
   FECVEN DATE,
   IDCLI INT,
   IDVEND INT,
   TIPPAGVEN CHAR(1),
   ESTVEN CHAR(1) DEFAULT 'A',
   CONSTRAINT venta_pk PRIMARY KEY (IDVEN),
   CONSTRAINT venta_cliente_fk FOREIGN KEY (IDCLI) REFERENCES persona(IDPER),
   CONSTRAINT venta_vendedor_fk FOREIGN KEY (IDVEND) REFERENCES persona(IDPER)
);
COMMIT;

/* Crear tabla VENTA_DETALLE */
CREATE TABLE venta_detalle (
   IDVENDET INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1,
   IDVEN INT,
   CODPROD CHAR(3),
   CANTVENDET INT,
   CONSTRAINT venta_detalle_pk PRIMARY KEY (IDVENDET),
   CONSTRAINT vd_venta_fk FOREIGN KEY (IDVEN) REFERENCES venta(IDVEN),
   CONSTRAINT vd_producto_fk FOREIGN KEY (CODPROD) REFERENCES producto(CODPROD)
);
COMMIT;

/* Ver estructura de tablas */
SELECT table_name, column_name, data_type, data_length
FROM USER_TAB_COLUMNS
WHERE table_name IN ('PERSONA','CATEGORIA','PRODUCTO','VENTA','VENTA_DETALLE')
ORDER BY table_name, column_id;

/* Listar relaciones (FOREIGN KEYS) */
SELECT a.table_name, a.constraint_name, a.column_name,
       c.owner AS ref_owner, c_pk.table_name AS ref_table, c_pk.constraint_name AS ref_constraint
FROM user_cons_columns a
JOIN user_constraints c 
ON a.owner = c.owner                     
AND a.constraint_name = c.constraint_name
JOIN user_constraints c_pk 
ON c.r_owner = c_pk.owner
AND c.r_constraint_name = c_pk.constraint_name
WHERE c.constraint_type = 'R'


/* Ver estructura de las tablas */
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME IN ('PERSONA','CATEGORIA','PRODUCTO','VENTA','VENTA_DETALLE');

select table_name from user_tables;


  